// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgYo7GTxyl6dKpowzPifcyWT5ZdlHxviE',
    appId: '1:779413046336:web:83278a7d208784f8e14ba5',
    messagingSenderId: '779413046336',
    projectId: 'todo-firebase-f28ca',
    authDomain: 'todo-firebase-f28ca.firebaseapp.com',
    storageBucket: 'todo-firebase-f28ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWNHKfI5kzsyhie8F8ogFhWnb10UKwKVE',
    appId: '1:779413046336:android:1b0ffa275380c024e14ba5',
    messagingSenderId: '779413046336',
    projectId: 'todo-firebase-f28ca',
    storageBucket: 'todo-firebase-f28ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdDpQk7TFFJkVINwGJuq21-8VK8H3SNxs',
    appId: '1:779413046336:ios:770b8669afc92aafe14ba5',
    messagingSenderId: '779413046336',
    projectId: 'todo-firebase-f28ca',
    storageBucket: 'todo-firebase-f28ca.appspot.com',
    iosClientId: '779413046336-t8lp098srkfpd4o41lcr82r6pg25itsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdDpQk7TFFJkVINwGJuq21-8VK8H3SNxs',
    appId: '1:779413046336:ios:770b8669afc92aafe14ba5',
    messagingSenderId: '779413046336',
    projectId: 'todo-firebase-f28ca',
    storageBucket: 'todo-firebase-f28ca.appspot.com',
    iosClientId: '779413046336-t8lp098srkfpd4o41lcr82r6pg25itsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebase',
  );
}
